export const FETCH_USER_ITEMS_START = "FETCH_USER_ITEMS_START";
export const FETCH_USER_ITEMS_SUCCESS = "FETCH_USER_ITEMS_SUCCESS";
export const FETCH_USER_ITEMS_FAILURE = "FETCH_USER_ITEMS_FAILURE";

export const FETCH_USER_SER = 'FETCH_USER_SER';
export const FETCH_USER_SER_SUCCESS = 'FETCH_USER_SER_SUCCESS';
export const FETCH_USER_SER_FAILURE = 'FETCH_USER_SER_FAILURE';
export const SET_USER_DETAIL = "SET_USER_DETAIL";