export const FETCH_USER_ITEMS_START = "FETCH_USER_ITEMS_START";
export const FETCH_USER_ITEMS_SUCCESS = "FETCH_USER_ITEMS_SUCCESS";
export const FETCH_USER_ITEMS_FAILURE = "FETCH_USER_ITEMS_FAILURE";

export const FETCH_USER_SER = 'FETCH_USER_SER';
export const FETCH_USER_SER_SUCCESS = 'FETCH_USER_SER_SUCCESS';
export const FETCH_USER_SER_FAILURE = 'FETCH_USER_SER_FAILURE';
export const SET_USER_DETAIL = "SET_USER_DETAIL";

// service list + detail
export const FETCH_SER_ITEMS_START = "FETCH_SER_ITEMS_START";
export const FETCH_SER_ITEMS_SUCCESS = "FETCH_SER_ITEMS_SUCCESS";
export const FETCH_SER_ITEMS_FAILURE = "FETCH_SER_ITEMS_FAILURE";

export const FETCH_SER_DETAIL = "FETCH_SER_DETAIL";
export const FETCH_SER_DETAIL_SUCCESS = "FETCH_SER_DETAIL_SUCCESS";
export const FETCH_SER_DETAIL_FAILURE = "FETCH_SER_DETAIL_FAILURE";
export const SET_SER_DETAIL = "SET_SER_DETAIL";

// package list + detail
export const FETCH_PACK_ITEMS_START = "FETCH_PACK_ITEMS_START";
export const FETCH_PACK_ITEMS_SUCCESS = 'FETCH_PACK_ITEMS_SUCCESS'
export const FETCH_PACK_ITEMS_FAILURE = 'FETCH_PACK_ITEMS_FAILURE'

export const FETCH_PACK_DETAIL = "FETCH_PACK_DETAIL";
export const FETCH_PACK_DETAIL_SUCCESS = 'FETCH_PACK_DETAIL_SUCCESS'
export const FETCH_PACK_DETAIL_FAILURE = "FETCH_PACK_DETAIL_FAILURE";


export const ADD_SER_TO_PACK = "ADD_SER_TO_PACK";