steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/WeOpenly/localgov.fyi.git']
- name: node:8
  entrypoint: npm
  args: ['install']
- name: 'ubuntu'
  args: ['mkdir', 'data']
- name: 'docker.io/library/python:2.7'
  args: ['python', 'localgov.fyi/pre_process.py']
  env: ['DSP_HOST=http://dsp.weopenly.com']
- name: node:8
  entrypoint: npm
  args: ['run', 'prodDeploy']
timeout: 3600s
options:
  diskSizeGb: 100