steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/WeOpenly/localgov.fyi.git']
- name: node:8
  entrypoint: npm
  args: ['install']
- name: 'ubuntu'
  args: ['mkdir', 'data']
- name: 'ubuntu'
  args: ['python', './pre_pocess.py']
- name: node:8.11.2
  entrypoint: npm
  args: ['run', 'prodDeploy']
timeout: 3600s
options:
  diskSizeGb: 100