steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/WeOpenly/localgov.fyi.git']
- name: 'docker.io/library/python:2.7'
  args: ['python', 'localgov.fyi/pre_process.py']
  env: ['DSP_HOST=http://dsp.weopenly.com']
- name: node:8
  dir: 'localgov.fyi'
  entrypoint: npm
  args: ['install', '--save']
# - name: node:8
#   dir: 'localgov.fyi'
#   entrypoint: node
#   args: ['./node_modules/.bin/gatsby', 'build', '--prefix-paths']
#   env: ['ACTIVE_ENV=production']
- name: ubuntu
  dir: 'localgov.fyi'
  args: ['mkdir', 'public']
- name: ubuntu
  dir: 'localgov.fyi'
  args: ['cp', '_redirects', 'public']
- name: gcr.io/cloud-builders/gsutil
  dir: 'localgov.fyi'
  args: ['cp', 'gs://evergov-netlify-env/.env', '.env']
- name: node:8
  entrypoint: node
  dir: 'localgov.fyi'
  args: ['-r', 'dotenv/config', './node_modules/.bin/netlify', 'deploy', '--dir=public']
timeout: 3600s
options:
  diskSizeGb: 100