export const REQUEST_USER_SAVED_ITEMS = 'REQUEST_USER_SAVED_ITEMS'
export const RECV_USER_SAVED_ITEMS = 'RECV_USER_SAVED_ITEMS'
export const FAILED_RECV_USER_SAVED_ITEMS = 'FAILED_RECV_USER_SAVED_ITEMS'

export const REQUEST_USER_SAVE_ITEM = 'REQUEST_USER_SAVE_ITEM'
export const SUCCESS_USER_SAVE_ITEM = 'SUCCESS_USER_SAVE_ITEM'
export const FAILED_USER_SAVE_ITEM = 'FAILED_USER_SAVE_ITEM'

export const ADD_LOCAL_SAVED_ORG = 'ADD_LOCAL_SAVED_ORG'
export const REMOVE_LOCAL_SAVED_ORG = 'REMOVE_LOCAL_SAVED_ORG'

export const ADD_LOCAL_SAVED_SERVICE = 'ADD_LOCAL_SAVED_SERVICE'
export const REMOVE_LOCAL_SAVED_SERVICE = 'REMOVE_LOCAL_SAVED_SERVICE'