export const TOGGLE_DELIVERY_DIALOG = 'TOGGLE_DELIVERY_DIALOG';

export const REQUEST_SERVICE_FLOW_BLUE_PRINT_SUMMARY = 'REQUEST_SERVICE_FLOW_BLUE_PRINT_SUMMARY';
export const SUCCESS_RECV_FLOW_BLUE_PRINT_SUMMARY = 'SUCCESS_RECV_FLOW_BLUE_PRINT_SUMMARY';
export const FAILED_RECV_FLOW_BLUE_PRINT_SUMMARY = 'FAILED_RECV_FLOW_BLUE_PRINT_SUMMARY';

export const SET_CURRENT_STEP_ID = 'SET_CURRENT_STEP_ID';
export const REQUEST_CREATE_SERVICE_FLOW = 'REQUEST_CREATE_SERVICE_FLOW';
export const SUCCESS_CREATE_SERVICE_FLOW = 'SUCCESS_CREATE_SERVICE_FLOW';
export const FAILED_CREATE_SERVICE_FLOW = 'FAILED_CREATE_SERVICE_FLOW';

export const REQUEST_UDPATE_SERVICE_FLOW = 'REQUEST_UDPATE_SERVICE_FLOW';
export const SUCCESS_UPDATE_SERVICE_FLOW = 'SUCCESS_UPDATE_SERVICE_FLOW';
export const FAILED_UPDATE_SERVICE_FLOW = 'FAILED_UPDATE_SERVICE_FLOW';

export const REQUEST_STEP_DETAILS = 'REQUEST_STEP_DETAILS';
export const SUCCESS_RECV_STEP_DETAILS = 'SUCCESS_RECV_STEP_DETAILS';
export const FAILED_RECV_STEP_DETAILS = 'FAILED_RECV_STEP_DETAILS';

export const REQUEST_STEP_DETAILS_SUBMIT = 'REQUEST_STEP_DETAILS_SUBMIT';
export const SUCCESS_SUBMIT_STEP = 'SUCCESS_SUBMIT_STEP';
export const FAILED_STEP_DETAILS_SUBMIT = 'FAILED_STEP_DETAILS_SUBMIT';
