export const TOGGLE_DELIVERY_DIALOG = 'TOGGLE_DELIVERY_DIALOG';


export const REQUEST_FLOW_STEPS = 'REQUEST_FLOW_STEPS';
export const SUCCESS_RECV_FLOW_STEPS = 'SUCCESS_RECV_FLOW_STEPS';
export const FAILED_RECV_FLOW_STEPS = 'FAILED_RECV_FLOW_STEPS';

export const REQUEST_CURRENT_USER_STEP = 'REQUEST_CURRENT_USER_STEP';
export const SUCCESS_RECV_CURRENT_USER_STEP = 'SUCCESS_RECV_CURRENT_USER_STEP';
export const FAILED_RECV_CURRENT_USER_STEP = 'SUCCESS_RECV_CURRENT_USER_STEP';