export const BUS_LIC_LOADING = "BUS_LIC_LOADING"; 
export const BUS_LIC_SUCCESS = 'BUS_LIC_SUCCESS';
export const BUS_LIC_FAILED = "BUS_LIC_FAILED";

export const PARK_TIK_LOADING = "PARK_TIK_LOADING";
export const PARK_TIK_SUCCESS = "PARK_TIK_SUCCESS";
export const PARK_TIK_FAILED = "PARK_TIK_FAILED";

export const TOLL_TIK_LOADING = "TOLL_TIK_LOADING";
export const TOLL_TIK_SUCCESS = "TOLL_TIK_SUCCESS";
export const TOLL_TIK_FAILED = "TOLL_TIK_FAILED";

export const DRIV_LIC_LOADING = 'DRIV_LIC_LOADING';
export const DRIV_LIC_SUCCESS = "DRIV_LIC_SUCCESS";
export const DRIV_LIC_FAILED = 'DRIV_LIC_FAILED';

export const VEH_REG_LOADING = "VEH_REG_LOADING";
export const VEH_REG_SUCCESS = "VEH_REG_SUCCESS";
export const VEH_REG_FAILED = "VEH_REG_FAILED";

export const SET_AUTO_REG = "SET_AUTO_REG";
export const CLEAR_ALL = "CLEAR_ALL";