export const ADM_GOOG_USER_LOGIN_START = 'ADM_GOOG_USER_LOGIN_START';
export const ADM_GOOG_USER_LOGIN_SUCCESS = 'ADM_GOOG_USER_LOGIN_SUCCESS';
export const ADM_GOOG_USER_LOGIN_FAILURE = 'ADM_GOOG_USER_LOGIN_FAILURE';
export const ADM_GOOG_LOG_OUT='ADM_GOOG_LOG_OUT';
export const ADM_USER_LOGIN_CHECK_START='ADM_USER_LOGIN_CHECK_START';
export const ADM_USER_LOGIN_CHECK_LOGGED_IN='ADM_USER_LOGIN_CHECK_LOGGED_IN';
export const ADM_USER_LOGIN_CHECK_NOT_LOGGED_IN='ADM_USER_LOGIN_CHECK_NOT_LOGGED_IN';