
export const REQUEST_AUTO_SUGGESTED_LOCS = 'REQUEST_AUTO_SUGGESTED_LOCS';
export const SUCCESS_RECV_AUTO_SUGGESTED_LOCS = 'SUCCESS_RECV_AUTO_SUGGESTED_LOCS';
export const FAILED_RECV_AUTO_SUGGESTED_LOCS = 'FAILED_RECV_AUTO_SUGGESTED_LOCS';

export const CLEAR_ALL = 'CLEAR_ALL';
export const SET_GOOG_LAT_LNG = 'SET_GOOG_LAT_LNG';
export const CLEAR_GOOG_LAT_LNG = 'CLEAR_GOOG_LAT_LNG';
export const UPDATE_SEARCH_TEXT_FOR_GOOG = 'UPDATE_SEARCH_TEXT_FOR_GOOG';

export const REQUEST_GOOG_SUGGESTED_LOCS = 'REQUEST_GOOG_SUGGESTED_LOCS';
export const SUCCESS_RECV_GOOG_SUGGESTED_LOCS = 'SUCCESS_RECV_GOOG_SUGGESTED_LOCS';
export const FAILED_RECV_GOOG_SUGGESTED_LOCS = 'FAILED_RECV_GOOG_SUGGESTED_LOCS';