export const TOGGLE_LOGIN_DIALOG = 'TOGGLE_LOGIN_DIALOG';
export const TOGGLE_REGISTER_DIALOG = 'TOGGLE_REGISTER_DIALOG';
export const TOGGLE_LOGIN_STATUS = 'TOGGLE_LOGIN_STATUS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUBMITTED = 'REGISTER_SUBMITTED';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REGISTER_VERIFICATION_REQUESTED = 'REGISTER_VERIFICATION_REQUESTED';
export const CHECK_CURRENT_USER_REQUEST_START = 'CHECK_CURRENT_USER_REQUEST_START';
export const CHECK_CURRENT_USER_REQUEST_FINISH = 'CHECK_CURRENT_USER_REQUEST_FINISH';