//  SELECTED SERVICES
export const ONE_USER_ADD_SELECTED_SERVICE_LOADING = 'ONE_USER_ADD_SELECTED_SERVICE_LOADING'
export const ONE_USER_ADD_SELECTED_SERVICE_LOADING_FAILED =
         "ONE_USER_ADD_SELECTED_SERVICE_LOADING_FAILED";
export const ONE_USER_ADD_SELECTED_SERVICE =
         "ONE_USER_ADD_SELECTED_SERVICE";

export const ONE_USER_SERVICES_SAVING = 'ONE_USER_SERVICES_SAVING';

export const ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING =
         "ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING";
export const ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING_FAILED =
         "ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING_FAILED";
export const ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS =
           "ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS";

export const ONE_USER_REMOVE_SELECTED_SERVICE =
         "ONE_USER_REMOVE_SELECTED_SERVICE";

export const ONE_USER_RECEIPTS_LOADING = 'ONE_USER_RECEIPTS_LOADING'
export const ONE_USER_RECEIPTS_SUCCESS = 'ONE_USER_RECEIPTS_SUCCESS'
export const ONE_USER_RECEIPTS_LOADING_FAILED = 'ONE_USER_RECEIPTS_LOADING_FAILED'

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";


