export const ONE_GOOG_USER_LOGIN_START = 'ONE_GOOG_USER_LOGIN_START'
export const ONE_GOOG_USER_LOGIN_SUCCESS = 'ONE_GOOG_USER_LOGIN_SUCCESS'
export const ONE_GOOG_USER_LOGIN_FAILURE = 'ONE_GOOG_USER_LOGIN_FAILURE'

export const ONE_USER_LOGIN_CHECK_START = 'ONE_USER_LOGIN_CHECK_START'
export const ONE_USER_LOGIN_CHECK_LOGGED_IN = 'ONE_USER_LOGIN_CHECK_LOGGED_IN'
export const ONE_USER_LOGIN_CHECK_NOT_LOGGED_IN = 'ONE_USER_LOGIN_CHECK_NOT_LOGGED_IN'

export const ONE_USER_SETUP_PAYMENT_LOADING =
         "ONE_USER_SETUP_PAYMENT_LOADING";
export const ONE_USER_SETUP_PAYMENT_SUCCESS =
         "ONE_USER_SETUP_PAYMENT_SUCCESS";
export const ONE_USER_SETUP_PAYMENT_FAILURE =
         "ONE_USER_SETUP_PAYMENT_FAILURE";

export const ONE_USER_SERVICES_UPDATE_STEP = "ONE_USER_SERVICES_UPDATE_STEP";

export const ONE_USER_LOGIN_USER_DETAILS_LOADING = 'ONE_USER_LOGIN_USER_DETAILS_LOADING'
export const ONE_USER_LOGIN_USER_DETAILS_LOADING_FAILED = 'ONE_USER_LOGIN_USER_DETAILS_LOADING_FAILED'
export const ONE_USER_LOGIN_ADD_USER_DETAILS = 'ONE_USER_LOGIN_ADD_USER_DETAILS'

export const ONE_USER_LOGIN_UPDATE_PREFS = "ONE_USER_LOGIN_UPDATE_PREFS";

export const ONE_USER_LOGIN_SERVICE_DETAILS_LOADING = 'ONE_USER_LOGIN_SERVICE_DETAILS_LOADING'
export const ONE_USER_LOGIN_SERVICE_DETAILS_LOADING_FAILED = 'ONE_USER_LOGIN_SERVICE_DETAILS_LOADING_FAILED'
export const ONE_USER_LOGIN_ADD_SERVICE_DETAILS = 'ONE_USER_LOGIN_ADD_SERVICE_DETAILS'

//  SELECTED SERVICES
export const ONE_USER_ADD_SELECTED_SERVICE_LOADING = 'ONE_USER_ADD_SELECTED_SERVICE_LOADING'
export const ONE_USER_ADD_SELECTED_SERVICE_LOADING_FAILED =
         "ONE_USER_ADD_SELECTED_SERVICE_LOADING_FAILED";
export const ONE_USER_ADD_SELECTED_SERVICE =
         "ONE_USER_ADD_SELECTED_SERVICE";

export const ONE_USER_SERVICES_SAVING = 'ONE_USER_SERVICES_SAVING';

export const ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING =
         "ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING";
export const ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING_FAILED =
         "ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS_LOADING_FAILED";
export const ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS =
           "ONE_USER_UPDATE_SELECTED_SERVICE_DETAILS";

export const ONE_USER_REMOVE_SELECTED_SERVICE =
         "ONE_USER_REMOVE_SELECTED_SERVICE";

export const ONE_USER_RECEIPTS_LOADING = 'ONE_USER_RECEIPTS_LOADING'
export const ONE_USER_RECEIPTS_SUCCESS = 'ONE_USER_RECEIPTS_SUCCESS'
export const ONE_USER_RECEIPTS_LOADING_FAILED = 'ONE_USER_RECEIPTS_LOADING_FAILED'

export const ONE_GOOG_LOG_OUT = 'ONE_GOOG_LOG_OUT'
