export const ONE_GOOG_USER_LOGIN_START = "ONE_GOOG_USER_LOGIN_START";
export const ONE_GOOG_USER_LOGIN_SUCCESS = "ONE_GOOG_USER_LOGIN_SUCCESS";
export const ONE_GOOG_USER_LOGIN_FAILURE = "ONE_GOOG_USER_LOGIN_FAILURE";

export const ONE_GOOG_LOG_OUT = "ONE_GOOG_LOG_OUT";

export const ONE_USER_LOGIN_CHECK_START = "ONE_USER_LOGIN_CHECK_START";
export const ONE_USER_LOGIN_CHECK_LOGGED_IN = "ONE_USER_LOGIN_CHECK_LOGGED_IN";
export const ONE_USER_LOGIN_CHECK_NOT_LOGGED_IN =
  "ONE_USER_LOGIN_CHECK_NOT_LOGGED_IN";

export const SET_LANDING_SELECTED_PLAN = "SET_LANDING_SELECTED_PLAN";
export const SET_LANDING_USER_TYPE = "SET_LANDING_USER_TYPE";

export const USER_DETAILS_UPDATE_START = "USER_DETAILS_UPDATE_START";
export const USER_DETAILS_UPDATE_SUCCESS = "USER_DETAILS_UPDATE_SUCCESS";
export const USER_DETAILS_UPDATE_FAILURE = "USER_DETAILS_UPDATE_FAILURE";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";

export const ONBOARD_UPDATE_STEP = "ONBOARD_UPDATE_STEP";
export const USER_SET_AUTHENTICATED = "USER_SET_AUTHENTICATED";