export const TOGGLE_STRIPE_MODAL= "TOGGLE_STRIPE_MODAL";

export const ONE_USER_SETUP_PAYMENT_LOADING = "ONE_USER_SETUP_PAYMENT_LOADING";
export const ONE_USER_SETUP_PAYMENT_SUCCESS = "ONE_USER_SETUP_PAYMENT_SUCCESS";
export const ONE_USER_SETUP_PAYMENT_FAILURE = "ONE_USER_SETUP_PAYMENT_FAILURE";

export const USER_PAYMENT_LOADING = 'USER_PAYMENT_LOADING'
export const USER_PAYMENT_LOADING_SUCCESS = 'USER_PAYMENT_LOADING_SUCCESS'
export const USER_PAYMENT_LOADING_FAILED = 'USER_PAYMENT_LOADING_FAILED'

export const ONE_USER_RECEIPTS_LOADING = "ONE_USER_RECEIPTS_LOADING";
export const ONE_USER_RECEIPTS_SUCCESS = "ONE_USER_RECEIPTS_SUCCESS";
export const ONE_USER_RECEIPTS_LOADING_FAILED =
"ONE_USER_RECEIPTS_LOADING_FAILED";
