export const USER_SERVICES_FETCH_LOADING = "USER_SERVICES_FETCH_LOADING";
export const USER_SERVICES_FETCH_SUCCESS = "USER_SERVICES_FETCH_SUCCESS";
export const USER_SERVICES_FETCH_FAILED = "USER_SERVICES_FETCH_FAILED";

export const UPDATE_SELECTED_SERVICES_START = "UPDATE_SELECTED_SERVICES_START";
export const UPDATE_SELECTED_SERVICES_SUCCESS = "UPDATE_SELECTED_SERVICES_SUCCESS";
export const UPDATE_SELECTED_SERVICES_FAILED = "UPDATE_SELECTED_SERVICES_FAILED";

export const UPDATE_FINALIZED_SERVICES_START = 'UPDATE_FINALIZED_SERVICES_START';
export const UPDATE_FINALIZED_SERVICES_SUCCESS =
         "UPDATE_FINALIZED_SERVICES_SUCCESS";
export const UPDATE_FINALIZED_SERVICES_FAILED =
         "UPDATE_FINALIZED_SERVICES_FAILED";
        
export const LOADING_SERVICE_TXNS = "LOADING_SERVICE_TXNS";
export const RECV_SERVICE_TXNS = "RECV_SERVICE_TXNS";
export const FAILED_RECV_SERVICE_TXNS = "FAILED_RECV_SERVICE_TXNS";