export const CLEAR_ALL = 'CLEAR_ALL';

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECV_SEARCH_RESULTS_SUCCESS = 'RECV_SEARCH_RESULTS_SUCCESS';
export const FAILED_RECV_SEARCH_RESULTS = 'FAILED_RECV_SEARCH_RESULTS';

