export const CLEAR_ALL = 'CLEAR_ALL';

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECV_SEARCH_RESULTS_SUCCESS = 'RECV_SEARCH_RESULTS_SUCCESS';
export const FAILED_RECV_SEARCH_RESULTS = 'FAILED_RECV_SEARCH_RESULTS';

export const REQUEST_NEARBY_ORGS = 'REQUEST_NEARBY_ORGS';
export const RECV_NEARBY_ORGS = 'RECV_NEARBY_ORGS';
export const FAILED_RECV_NEARBY_ORGS = 'FAILED_RECV_NEARBY_ORGS';