export const REQUEST_AREA_GUESS = 'REQUEST_AREA_GUESS';
export const SUCCESS_RECV_AREA_GUESS = 'SUCCESS_RECV_AREA_GUESS';
export const FAILED_RECV_AREA_GUESS = 'FAILED_RECV_AREA_GUESS';

export const CLEAR_ALL = 'CLEAR_ALL';
export const APP_READY = "APP_READY";

export const REQUEST_AREA_SERVICES = 'REQUEST_AREA_SERVICES';
export const SUCCESS_RECV_AREA_SERVICES = 'SUCCESS_RECV_AREA_SERVICES';
export const FAILED_RECV_AREA_SERVICES = 'FAILED_RECV_AREA_SERVICES';


export const UPDATE_SERVICE_SEARCH_TEXT = 'UPDATE_SERVICE_SEARCH_TEXT';
export const UPDATE_GOOG_LOCATION_SEARCH_TEXT = 'UPDATE_GOOG_LOCATION_SEARCH_TEXT';
export const SELECT_SERVICE_TEMPLATE_ID = 'SELECT_SERVICE_TEMPLATE_ID';
export const SELECT_GOOG_LOCATION = 'SELECT_GOOG_LOCATION';
