export const TOGGLE_SEARCH_RESULTS_LAYOUT = 'TOGGLE_SEARCH_RESULTS_LAYOUT';

export const REQUEST_APP_META = 'REQUEST_APP_META';
export const RECV_APP_META = 'RECV_APP_META';
export const RECV_APP_META_FAILED = 'RECV_APP_META_FAILED';

export const UPDATE_INPUT = 'UPDATE_INPUT';
export const REQUEST_SEARCH_SUGGESTIONS = 'REQUEST_SEARCH_SUGGESTIONS';
export const RECV_SEARCH_SUGGESTIONS_FAILED = 'RECV_SEARCH_SUGGESTIONS_FAILED';
export const RECV_SEARCH_SUGGESTIONS_SUCCESS = 'RECV_SEARCH_SUGGESTIONS_SUCCESS';

export const UPDATE_SERVICE_INPUT = 'UPDATE_SERVICE_INPUT';
export const REQUEST_SERVICE_SUGGESTIONS = 'REQUEST_SERVICE_SUGGESTIONS';
export const RECV_SERVICE_SUGGESTIONS_FAILED = 'RECV_SERVICE_SUGGESTIONS_FAILED';
export const RECV_SERVICE_SUGGESTIONS_SUCCESS = 'RECV_SERVICE_SUGGESTIONS_SUCCESS';

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECV_SEARCH_RESULTS_SUCCESS = 'RECV_SEARCH_RESULTS_SUCCESS';
export const RECV_SEARCH_RESULTS_FAILED = 'RECV_SEARCH_RESULTS_FAILED';
export const RECV_SEMANTIC_SEARCH_RESULTS = 'RECV_SEMANTIC_SEARCH_RESULTS';

export const SELECT_ORGANIZATION = 'SELECT_ORGANIZATION';
