export const ONE_SERVICES_LOADING = "ONE_SERVICES_LOADING";
export const ONE_SERVICES_LOADING_SUCCESS = "ONE_SERVICES_LOADING_SUCCESS";
export const ONE_SERVICES_LOADING_FAILED = "ONE_SERVICES_LOADING_FAILED";

export const FETCH_INDIV_PLAN_DETAILS_START = "FETCH_INDIV_PLAN_DETAILS_START";
export const RECV_INDIV_PLAN_DETAILS = "RECV_INDIV_PLAN_DETAILS";
export const FAILED_RECV_INDIV_PLAN_DETAILS = "FAILED_RECV_INDIV_PLAN_DETAILS";

export const FETCH_BUSI_PLAN_DETAILS_START = "FETCH_BUSI_PLAN_DETAILS_START";
export const RECV_BUSI_PLAN_DETAILS = "RECV_BUSI_PLAN_DETAILS";
export const FAILED_RECV_BUSI_PLAN_DETAILS = "FAILED_RECV_BUSI_PLAN_DETAILS";
