export const QP_APP_READY = 'QP_APP_READY' 
export const QP_CHANGE_STEP = 'QP_CHANGE_STEP'

export const QP_CREATE_SUB_START = 'QP_CREATE_SUB_START'
export const QP_CREATE_SUB_SUCCESS = 'QP_CREATE_SUB_SUCCESS'
export const QP_CREATE_SUB_FAILED = 'QP_CREATE_SUB_FAILED'

export const QP_ANALYSE_DOC_START = 'QP_ANALYSE_DOC_START'
export const QP_ANALYSE_DOC_SUCCESS = 'QP_ANALYSE_DOC_SUCCESS'
export const QP_ANALYSE_DOC_FAILED = 'QP_ANALYSE_DOC_FAILED'

export const QP_SUBMIT_START = 'QP_SUBMIT_START'
export const QP_SUBMIT_SUCCESS = 'QP_SUBMIT_SUCCESS'
export const QP_SUBMIT_FAILED = 'QP_SUBMIT_FAILED'

export const UPDATE_USER_PRICE = 'UPDATE_USER_PRICE'
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL'

export const QP_ANON_USER_LOAD_BEGIN = 'QP_ANON_USER_LOAD_BEGIN';
export const QP_ANON_USER_SUCCESS = 'QP_ANON_USER_SUCCESS';
export const QP_ANON_USER_FAILURE = 'QP_ANON_USER_FAILURE'
