export const ONE_GOOG_USER_LOGIN_START = 'ONE_GOOG_USER_LOGIN_START'
export const ONE_GOOG_USER_LOGIN_SUCCESS = 'ONE_GOOG_USER_LOGIN_SUCCESS'
export const ONE_GOOG_USER_LOGIN_FAILURE = 'ONE_GOOG_USER_LOGIN_FAILURE'

export const ONE_USER_LOGIN_CHECK_START = 'ONE_USER_LOGIN_CHECK_START'
export const ONE_USER_LOGIN_CHECK_LOGGED_IN = 'ONE_USER_LOGIN_CHECK_LOGGED_IN'
export const ONE_USER_LOGIN_CHECK_NOT_LOGGED_IN = 'ONE_USER_LOGIN_CHECK_NOT_LOGGED_IN'

export const ONE_GOOG_LOG_OUT = 'ONE_GOOG_LOG_OUT'
