export const REQUEST_AUTO_SUGGESTED_LOCS = "REQUEST_AUTO_SUGGESTED_LOCS";
export const SUCCESS_RECV_AUTO_SUGGESTED_LOCS =
  "SUCCESS_RECV_AUTO_SUGGESTED_LOCS";
export const FAILED_RECV_AUTO_SUGGESTED_LOCS =
  "FAILED_RECV_AUTO_SUGGESTED_LOCS";

export const CLEAR_ALL = "CLEAR_ALL";
export const SET_AUTO_REGION = "SET_AUTO_REGION";
